[programs.devnet]
dao = "5TY1ftQBHvXTxuccJSEbVBQMTYdFhKf9JJCZvFry6BYx"
register = "BkZnVzwwiCfvZaF9EL57SjwS1dJquRJ596x8DGckrvvV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test ./tests/test-cpi.test.ts"
