[programs.devnet]
cyber_wave = "ETmGRPZESjms15H8QWeqE9oGk7pKKmYENv6MBSKEiD1A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn test"
