[programs.devnet]
dao = "GdySSAQ5BGoa11mUHoHDeJZdmyZQbreguyBJLu8XMvS9"
register = "7xESfHY92n9LZ5GteyQX5hsJrj8kKfeYssh69TL1w3BM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test ./tests/test-cpi.test.ts"
